### ISSUE TITLE
How to understand multi-workspace detection?

### ISSUE THREAD

**Issue by adrianwnuk** [totmicro/atlantis-yaml-generator#4]
How to understand logic behind multi-workspace detection? What is the detection requirement?

```
./atlantis-yaml-generator -w single -q backend.tf -e stdout
version: 3
automerge: true
parallel_apply: true
parallel_plan: true
projects:
    - name: .
      workspace: default
      workflow: single-workspace
      dir: .
      autoplan:
        enabled: true
        when_modified:
            - '**/*.tf'
            - '**/*.tfvars'
            - '**/*.json'
            - '**/*.tpl'
            - '**/*.tmpl'
            - '**/*.xml'
```
```
./atlantis-yaml-generator -w multi-workspace -q backend.tf -e stdout                                                                    
version: 3
automerge: true
parallel_apply: true
parallel_plan: true
projects: []
```

```
./atlantis-yaml-generator -w multi-workspace -q workspace_vars -e stdout                                                                 
version: 3
automerge: true
parallel_apply: true
parallel_plan: true
projects: []

```
```
.
├── README.md
├── backend.tf
├── env-vars.tf
├── locals.tf
├── provider.tf
├── terraform.tfvars
├── users.tf
└── vars.tf

0 directories, 9 files
```
